# -- auto-generated by prepare_test_coverage --
import sys
from pathlib import Path
from unittest.mock import MagicMock

# 1. Add source root to sys.path so imports like 'import sub.hello' work.
_src_root = Path(r"C:\Users\Nathan Cerisara\Documents\github\nasong\src\nasong")
if str(_src_root) not in sys.path:
    sys.path.insert(0, str(_src_root))

# 2. Globally mock sounddevice to prevent CFFI errors and hardware access
if "sounddevice" not in sys.modules:
    mock_sd = MagicMock()
    # Mock common classes/methods used in the project
    mock_sd.OutputStream.return_value = MagicMock()
    mock_sd.query_devices.return_value = []
    sys.modules["sounddevice"] = mock_sd
