# -- auto-generated by prepare_test_coverage --
import sys
from pathlib import Path

# Add source root to sys.path so imports like 'import sub.hello' work.
_src_root = Path(r"C:\Users\Nathan Cerisara\Documents\github\nasong\src\nasong")
if str(_src_root) not in sys.path:
    sys.path.insert(0, str(_src_root))
